;========================= - Setting - =========================;
[SHORTCUTS]
    dspaz = explore "D:\Projects\AutoHotKey"
    dnets = explore "D:\Desktop-Toolbar\Netzwerk"
    dToolbar = explore "D:\Desktop-Toolbar"
    COH = CoH12_RunStart.ahk
    GTFO = GTFO_Terminal_cmd.ahk
    Helldiver = .\Helldivers\Helldivers_Run.ahk
    Tap_Ninja = Tap_Ninja_AutoClicker_Space.ahk
    # TPN = 0
    #SOB = "E:\Games\Battle.net\Battle.net Launcher.exe" --setregion=US
    SOB = "D:\Program Files (x86)\Battle.net\Battle.net Launcher.exe"
    Steam = "C:\Program Files (x86)\Steam\steam.exe" -dev
    # sps = 0
    WeMod = C:\Users\Hansen\AppData\Local\WeMod\WeMod.exe
    KeePass = E:\Program Files (x86)\KeePass-2.56-Portable\KeePass.exe
    # KP = 0
    Epic = D:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe
    StartUp = shell:startup
    # qidong = 0
    nu = E:\Program Files (x86)\Netease\UU\Netease\UU\uu_launcher.exe
    nv = D:\Program Files\v2rayN-windows-64-SelfContained-With-Core\v2rayN.exe
    # Desktop-Toolbar = 0
    # DT = 0
    config = config.ini

[AKA]
    TPN = Tap_Ninja
    sps = Steam
    KP = KeePass
    qidong = StartUp
    Desktop-Toolbar = dToolbar
    DT = dToolbar
    Toolbar = dToolbar
    spaz = dspaz
    netg = dnets