;========================= - Setting - =========================;
[SHORTCUTS]
    dspaz = explore "D:\Projects\AutoHotKey"
    dnets = explore "D:\Desktop-Toolbar\"
    dToolbar = explore "D:\Desktop-Toolbar"
    StartUp = shell:startup
    # Desktop-Toolbar = 0
    # DT = 0
    config = config.ini

[AKA]
    TPN = Tap_Ninja
    sps = Steam
    KP = KeePass
    qidong = StartUp
    Desktop-Toolbar = dToolbar
    DT = dToolbar
    Toolbar = dToolbar
    spaz = dspaz
    netg = dnets
