# 标记 Git 跳过这个文件的工作区修改
# 在项目目录用Git Bash执行：
# git update-index --skip-worktree config.ini

;========================= - Setting - =========================;
[SHORTCUTS]
    dspaz = explore "D:\Projects\AutoHotKey"
    dnets = explore "D:\Desktop-Toolbar\"
    dToolbar = explore "D:\Desktop-Toolbar"
    StartUp = shell:startup
    # Desktop-Toolbar = 0
    # DT = 0
    config = config.ini

[AKA]
    sps = Steam
    qidong = StartUp
    Desktop-Toolbar = dToolbar
    DT = dToolbar
    Toolbar = dToolbar
    spaz = dspaz
